### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by opemvbs** [frux-c/ValorantBot#2]
Got this error, I already put the new required play_button.png
```
Traceback (most recent call last):
  File "C:\Users\-\Desktop\ValorantBot-main\main.py", line 534, in run
    self.find_home_play()
  File "C:\Users\-\Desktop\ValorantBot-main\main.py", line 430, in find_home_play
    self.click(PLAY_MODE.x,PLAY_MODE.y)
AttributeError: 'NoneType' object has no attribute 'x'
```

**Comment by frux-c** [comment]
Hi, 
Basically, there error is happening because it can't find the play button image, resulting in a None type to be returned. and None types has no attributes.
Try decreasing the confidence level or maybe using grayscale to combat this issue. It may also be screen or game resolution difference
